//Change this mongoose model to mssql
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

// Here I define the db schema
var schema = new Schema({
  // This ID , behind the scenes..links to the User's collection ...Here I set a reference to the User model
    user: {type: Schema.Types.ObjectId, ref: 'User'},
    cart: {type: Object, required: true},
    address: {type: String, required: true},
    name: {type: String, required: true},
    paymentId: {type: String, required: true} // This is an id generated by Stripe
});

module.exports = mongoose.model('Order', schema);
